name = 'pyiridium9602'
version = '1.2.3'
description = 'Python 3 iridium communication library for the iridium 9602 modem.'
url = 'https://github.com/justengel/pyiridium9602'
author = 'Justin Engel'
author_email = 'jengel@sealandaire.com'
